config/routes.rb
Sillisibs::Application.routes.draw do
  resources :families
  resources :users
  resources :sessions, only: [:new,:create,:destroy]

  root 'static_pages#home'

  match '/checkin', to: 'users#signin', via: 'get'
  match '/admin', to: 'users#admin', via: 'get'
  match '/search', to: 'users#search', via: 'get'

  match '/signout', to: 'sessions#destroy', via: 'delete'
  
end
  

app/models/family.rb
class Family < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :family
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController

	def index
	end
	
	def show
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	 before_filter CASClient::Frameworks::Rails::Filter

	 def new
	 	netid
	 	if netid == 'dmc225'
	 		flash[:success] = "You have logged in as an admin!"
	 		redirect_to admin_path
	 	else
	 		flash[:success] = "Successful signin!"
	 		redirect_to search_path
	 end

	 def destroy
	 	sign_out_CAS
	 end

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user

	def signin
	end

	def show
		@user = User.find_by(:id => params[:id])
		@family = @user.family
	end

	def admin
	end

	def search
	end

	private 

	def signed_in_user
    unless signed_in?
      store_location
      redirect_to :root, notice: "Please sign in with CAS."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #Pulling the netid
  def netid
    @netid ||= session[:cas_user]
  end


	#signing in methods
  # def sign_in
  #     remember_token = User.new_remember_token
  #     cookies.permanent[:remember_token] = remember_token
  #     user.update_attribute(:remember_token, User.digest(remember_token))
  #     @current_user = user 
  # end

  def signed_in?
    !session[:cas_user].nil?
  end

#signing out method  
  # def sign_out_locally
  #   current_user.update_attribute(:remember_token,
  #                                 User.digest(User.new_remember_token))
  #   cookies.delete(:remember_token)
  #   self.current_user = nil
  # end

  def sign_out_CAS
    CASClient::Frameworks::Rails::Filter.logout(self)
  end

#current user methods
  # def current_user=(user)
  #   @current_user = user
  # end

  # def current_user 
  #   remember_token = User.digest(cookies[:remember_token])
  #   @current_user ||= User.find_by(remember_token: remember_token)
  # end

  # def current_user?(user)
  #   user == current_user
  # end

#kind redirection when not signed in
  def store_location
    session[:return_to] = request.url if request.get?
  end

  def redirect_back_or(default)
    redirect_to (session[:return_to] || default)
    session.delete(:return_to)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/families/index.html.erb
<div id="attendance">Attendance</div>
<div class="container">
	<% Family.all.each do |family| %>
		<div class="block">
		<%= render 'shared/familyview', :@family => family %>
		</div>
	<% end %>
</div>
<div class="back">
	<%= link_to "Back", admin_path, class:'done-button pure-button' %>
</div>

app/views/families/show.html.erb
I am a show families page.
<br>
	<%= link_to "Sign Out", signout_path, class:'button-xlarge pure-button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sillisibs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">


</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_familyview.html.erb
<div class="table-responsive" id="table">
	<table class="table">
		<tr><div id="title"><b>Family <%= @family.id %></b></div></tr>
		<% @family.users.each do |member| %>
			<tr>
				<td><%= member.name %></td>
				<td>
				<%= member.presence.capitalize %>
				</td>
			<tr>
		<% end %>
	</table>		
</div>

app/views/shared/_viewport.html.erb
<div class="viewport">
	<img class="silliman" src="http://silliman.yalecollege.yale.edu/sites/default/files/images/sillimanbanners5.jpg">
	<h1><span>SILLISIBS</span></h1>
</div>

app/views/static_pages/home.html.erb
<%= render 'shared/viewport' %>
<center>
	<h2>Only one of the best organizations at Yale.<br>And the admins are these lovely people named Dana and Melia.</h2>
	<%= link_to "Sign In", new_session_path, class:'button-xlarge pure-button' %>
</center>

app/views/users/admin.html.erb
<%= render 'shared/viewport' %>
<center>
	<h2>So this will be where the admin dash will be. This way, we can more easily track where everything is happening.</h2>
	<%= link_to "Check In", checkin_path, class:'button-xlarge pure-button' %>
	<%= link_to "Attendance", families_path, class:'button-xlarge pure-button' %>
	<br>
	<%= link_to "Sign Out", signout_path, method: "delete", class:'button-xlarge pure-button' %>
</center>

app/views/users/search.html.erb
<%= render 'shared/viewport' %>
I am a search page.

app/views/users/show.html.erb
<div class="name">
	<h1><%= @user.name %></h1>
</div>
<div class="pure-g">
	<div class="pure-u-2-5">
		<div class="family">
			<%= render 'shared/familyview' %>
		</div>
	</div>
	<div class="pure-u-3-5">
		<div class="chart">
		 <h2>Your family will be meeting here.</h2>
		 <h2>Here will be a picture of the dining hall.</h2>
		</div>
	</div>
	<div class="pure-u-3-5">
		<div class="link">
		<h1>Stay updated!<br>sillisibs.herokuapp.com</h1>
		</div>
	</div>
	<div class="pure-u-2-5">
		<div class="done">
			<%= link_to "Done!", checkin_path, class:'done-button pure-button' %>
		</div>
	</div>
</div>

app/views/users/signin.html.erb
<%= render 'shared/viewport' %>
<center>
	<h1>Check In!</h1>
	<h2>Please type your name below.</h2>
	<%= link_to "Let's say you finished.", user_path(:id => 1), class:'button-xlarge pure-button' %>
	<br><br>
	<%= link_to "Dashboard", admin_path, class:'button-xlarge pure-button' %>
</center>